[package]
name = "date_diff"
version = "0.1.0"
authors = ["Luciano Bestia <luciano.bestia@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
date_diff_lib = { path = "../date_diff_lib" }
clap = "2.32.0"
ansi_term = "0.11.0"

